twist_mux:
  ros__parameters:
    topics:
      following:
        topic: cmd_vel_follow
        timeout: 0.5 
        priority: 50
      joystick:
        topic: cmd_vel_joystick
        timeout: 0.5
        priority: 100
    locks:
      follow_lock:
        topic: follow_bool
        timeout: 
        pirority: 
      teleop_lock:
        topic: follow_bool
        timeout: 
        pirority: 